
#Puerto para ejecutar el proyecto
server:
  port : 8090
spring:
  #Coneccion a base de datos
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/centralDB
    username: postgres
    password: postgres
  #Base de datos (por defecto)
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  #Thymeleaf para el motor de plantillas
  #-------------------------------------
  thymeleaf:
    cache: false
    #Codificacion de los archivos de la plantilla
    encoding: UTF-8
    #Modo de plantilla a aplicar
    mode: HTML
    #Modo de enviar la plantilla
    servlet:
      content-type: text/html
    #Extension de archivos
    suffix: .html
